### PR TITLE
[infra-proxy-read-only] fixed the scroll bar for the infra create org modal

### PR DESCRIPTION
**Pull request by vinay033**
Signed-off-by: Vinay Sharma <vsharma@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
Create org modal scroll bar is the same as other modal scroll bars.

### :chains: Related Resources
https://github.com/chef/automate/issues/4623
### :+1: Definition of Done
I have added CSS changes to fix the create org modal scroll bar.
### :athletic_shoe: How to Build and Test the Change
To load sample data:
- Load data into the infra views using `infra_service_load_sample_data` in hab studio (ref: [adding_test_data](https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md))
- Enable the Chef Infra Server Views in the magic menu by typing **feat** anywhere in the automate ui

if you have sample data for the infra servers than 
go to >>  infrastructure tab >> click on Chef server on left side navigation bar >> click to any server where you can see the button `add chef organization` 
### :camera: Screenshots, if applicable
**before fix** 
org-modal-scrollbar
**after fix**
org-modal-scrollbar-fixed

### CODE REVIEW

**Review by vivekshankar1 — APPROVED** [review]
Thank you. Its working as expected

**Comment by rickmarry** [comment]
I like this change.  In fact, I believe that is works better than some of the other model boxes that we have, specifically when zooming the browser window, in this one that you've changed, the zoom maintains the height of the model window and places scroll bar **(if and only if needed)**.
Now, if you want an example of a modal that misbehaves as I've described, take a look at this one: go to >> infrastructure tab >> click on Chef server on left side navigation bar >> click on add chef-server  Notice how when we zoom in, the model does not maintain it's height and no scroll bar is present when needed.. in fact, it's impossible to scroll the page at all.  I believe that the other models should behave the way you've made this one behave. 

nice work!  thank you!  
The one critique I would point out is that you could have made the modal screen a little bit taller so that it reduces the need for the scroll bar as much as possible. there is some spare space above and below that can be used for this.

**Review by rickmarry — CHANGES_REQUESTED** [review]
could make the modal a bit taller to avoid scroll in more resolutions

**Comment by vinay033** [comment]
> could make the modal a bit taller to avoid scroll in more resolutions

hello @rickmarry 
I have incorporated the review comment changes and increased the height of the modal for the add org. please check in the screenshot.
Before the change
org-previous

After the change
org-after

**Comment by rickmarry** [comment]
> I have incorporated the review comment changes and increased the height of the modal for the add org. please check in the screenshot.

perfect.. thank you

**Review by rickmarry — APPROVED** [review]
thank you @vinay033

**Pull request merged**
