### PR TITLE
Patch for policies value and added test

### PR DESCRIPTION
**Pull request by SEAjamieD**
### :nut_and_bolt: Description: What code changed, and why?
In the event feed guitar strings on the event feed dashboard, the word 'policy' was getting pluralized to 'policys' - this corrects pluralization to 'policies'

### :chains: Related Resources
fixes https://github.com/chef/automate/issues/2892

### :+1: Definition of Done
Tooltips no longer show the work "policys" when they are plural, and now reflect the correct. "policies"

### :athletic_shoe: How to Build and Test the Change
build component/automate-ui-devproxy && start_all_services
make serve

in hab studio run the following a few times:
`cat components/ingest-service/examples/actions/policy_update.json | jq --arg date "$(date +%FT%TZ -d '1 day ago')" '.recorded_at = $date' | send_chef_data_raw lb`

navigate to https://a2-dev.test/dashboards/event-feed
Hover over the guitar string icons in the following photo until you see the tooltip pop up.
Screen Shot 2020-04-16 at 12 07 59 PM

Wherever there has been an update to a policy, we should the name reflected as `policy` if singular and `policies` if plural.

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
after:
Screen Shot 2020-04-16 at 12 04 24 PM
Screen Shot 2020-04-16 at 12 04 31 PM

### CODE REVIEW

**Comment by SEAjamieD** [comment]
@vjeffrey / @chef/ux-team 

We've got a few options for this fix.  The first is something like what I added.  Its a very simple patch and will work fine for now, but has the possibility of returning incorrect pluralizations again in the future.

Second is copying the pluralize function from https://github.com/chef/automate/blob/master/components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts#L123 - this will take a little bit longer because there are typescript complaints to work through re: RexExp vs String.  It is a little more hearty will definitely last longer.

the Third option, which I feel is the "right" thing to do, Is to take the larger function `getEventTypeLabel()` which is nearly identical out of the event feed and the types files and move them to a top level Event Feed file, export them, and use them in both the locations they are currently being used.  This is the one that will take the longest - but I'd argue is the right way to do it.

I guess that leaves a 4th option - which is more time respective, which is to make a new ticket to refactor this in the future.

thoughts?

**Comment by vjeffrey** [comment]
i think i would vote for option 4 + option 3, in other words, get this in, make an issue to do option 3 -- id love to hear other thoughts tho!

**Comment by SEAjamieD** [comment]
@vjeffrey - Thanks for adding that!  I had written down all the instructions to test and never clicked save 😂

**Comment by msorens** [comment]
How about one more option? 😁 Use our general-purpose `pluralize` pipe (components/automate-ui/src/app/pipes/pluralize.pipe.ts). I suspect you discounted this @SEAjamieD because you are in TypeScript rather than in a template. But pipes can easily be used on the TypeScript side, too.

See:
1. [Is it possible to use a pipe in the code?](https://stackoverflow.com/questions/35159079/is-it-possible-to-use-a-pipe-in-the-code)
2. Example in our code base: https://github.com/chef/automate/blob/59410910c85ee2cb32ecaafb10d713103baecfbc/components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.ts#L37

**Comment by SEAjamieD** [comment]
> How about one more option? 😁 Use our general-purpose `pluralize` pipe (components/automate-ui/src/app/pipes/pluralize.pipe.ts). I suspect you discounted this @SEAjamieD because you are in TypeScript rather than in a template. But pipes can easily be used on the TypeScript side, too.

That's _exactly_ what I did!  I had no idea!  Thanks for the info - i'll give that a try first 👍

**Pull request merged**
