### PR TITLE
Fix automate-workflow-ctl habitat plan paths

### PR DESCRIPTION
**Pull request by btm**
I'm unsure what changed, but these won't build for me locally without
more specific paths.

### CODE REVIEW

**Comment by btm** [comment]
Later instead of the pattern of `automate/components/automate-workflow-ctl$ hab pkg build habitat` I started using `automate$ hab studio enter` followed by `cd automate/components/automate-workflow-ctl ; build` and that made the difference for some packages, but this doesn't seem wrong.

**Comment by stevendanna** [comment]
My guess is `hab pkg build ./` would have worked there.

> I wonder if using the HAB_CACHE_SRC_PATH like that is safe. It could have stale files, if we keep copying into it. Not sure if our builds are sufficiently isolated (i.e. their HAB_CACHE_SRC_PATH is nuked)...

I'm not sure I am understanding your concern here.  Based on my reading of this change, if this is a problem then it is a problem with the existing code as well.

**Comment by stevendanna** [comment]
My guess is `hab pkg build ./` would have worked there.

> I wonder if using the HAB_CACHE_SRC_PATH like that is safe. It could have stale files, if we keep copying into it. Not sure if our builds are sufficiently isolated (i.e. their HAB_CACHE_SRC_PATH is nuked)...

I'm not sure I am understanding your concern here.  Based on my reading of this change, if this is a problem then it is a problem with the existing code as well.

**Comment by srenatus** [comment]
> Based on my reading of this change, if this is a problem then it is a problem with the existing code as well.

Yup, my thought wasn't really related to this change, sorry.

**Pull request merged**
