### PR TITLE
Changes in backend deployment with respect to Managed Services 

### PR DESCRIPTION
**Pull request by shanmugapriya-tr**
### :nut_and_bolt: Description: What code changed, and why?

This PR contains changes to setup only the required Infra and services as part of the deployment. If the setup_managed_services variable is set to true (default is false for A2HA), internal postgres and elasticsearch modules are not set up. 

JIRA Tickets : 

https://chefio.atlassian.net/browse/KRATOS-41
https://chefio.atlassian.net/browse/KRATOS-6

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### CODE REVIEW

**Review by punitmundra — COMMENTED** [review]
Pipeline is failing

**Comment by shanmugapriya-tr** [comment]
@punitmundra - Branch is rebased with main. Errors in pipeline are not related to changes done as part of this PR

**Review by punitmundra — COMMENTED** [review]
It has showing the change from other PR as well.
can you make it correct. it is showing the files changed 197

**Comment by shanmugapriya-tr** [comment]
Closing and re-raising

**Pull request closed without merging**
