### PR TITLE
Image Updates using UserDocs

### PR DESCRIPTION
**Pull request by dishanktiwari2501**
### :nut_and_bolt: Description: What code changed, and why?

The images on the website will be updated automatically using UserDocs. The changes will take place whenever there is a change in the screenshot.

### :+1: Definition of Done

Trial on the image update to update them locally and check it works for us.

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### CODE REVIEW

**Review by kagarmoe — APPROVED** [review]
On @vivekshankar1 's comment: Let's skip the context on this image & set UserDocs to capture just the modal without the background.

**Review by vivekshankar1 — CHANGES_REQUESTED** [review]
Screenshot 2022-01-05 at 12 31 28 PM

Hi @dishanktiwari2501 , this image has errors in behind and also the content is covered by the modal, Could we use a better image

**Review by kagarmoe — CHANGES_REQUESTED** [review]
Retake one image--see @vivekshankar1 's comment and my suggestion

**Comment by kagarmoe** [comment]
@dishanktiwari2501 Do you have an update?

**Review by kagarmoe — CHANGES_REQUESTED** [review]
Some of the images don't line up with the filenames. My guess is that automation isn't firing correctly.

**Comment by kagarmoe** [comment]
@dishanktiwari2501 -- Do you have a follow-up about the images?

**Review by kagarmoe — APPROVED** [review]

**Pull request merged**
