### PR TITLE
Fixed references to Chef Server need to be Chef Infra Server or Infra Server

### PR DESCRIPTION
**Pull request by vinay033**
### :nut_and_bolt: Description: What code changed, and why?
The new Infra view features almost exclusively refer to Chef Infra Server as the Chef Server.
The views in Automate need to match this branding.
### :chains: Related Resources
https://github.com/chef/automate/issues/4878
### :+1: Definition of Done
I have replaced `Chef Server` to 'Chef Infa Server' in infra views.
### :athletic_shoe: How to Build and Test the Change
```
STEP 1
inside the hab studio

[default:/src:0]# build components/automate-ui-devproxy/
[default:/src:0]# start_automate_ui_background
[default:/src:0]# start_all_services

STEP 2
open new window
go to automate UI path

$ cd components/automate-ui
and run the command 

npm run serve:hab

navigate to `https://a2-dev.test/infrastructure/chef-servers`
```

```
Go to the `infrastructure tab` from the top navigation bar then you can see the `Chef Infra Server`
Where you can see the changes
```

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable
Chef Automate (16)

### CODE REVIEW

**Comment by tas50** [comment]
Looks good from the product side of things. Thanks @vinay033

**Comment by SEAjamieD** [comment]
Everything looks good to me, waiting until the pipeline clears to approve 👍

**Comment by SEAjamieD** [comment]
@vinay033 - e2e is failing in the pipeline, looks like it might need an update as a result of the naming updates

```
Running:  ui/infra-proxy/chef-server-details.spec.ts                                    (23 of 31)
--
  |  
  | chef server details
  | chef server details page
  | 1) displays server details
  | ✓ can check empty org list (91ms)
  | ✓ can add a organization (1389ms)
<--- removed output that isn't needed for this error --->
  |  
  |  
  | 12 passing (47s)
  | 1 failing
  |  
  | 1) chef server details chef server details page displays server details:
  | CypressError: Timed out retrying: Expected to find content: 'Chef Servers' within the element: <chef-breadcrumbs> but never did.


```

**Comment by vinay033** [comment]
> @vinay033 - e2e is failing in the pipeline, looks like it might need an update as a result of the naming updates
> 
> ```
> Running:  ui/infra-proxy/chef-server-details.spec.ts                                    (23 of 31)
> --
>   |  
>   | chef server details
>   | chef server details page
>   | 1) displays server details
>   | ✓ can check empty org list (91ms)
>   | ✓ can add a organization (1389ms)
> <--- removed output that isn't needed for this error --->
>   |  
>   |  
>   | 12 passing (47s)
>   | 1 failing
>   |  
>   | 1) chef server details chef server details page displays server details:
>   | CypressError: Timed out retrying: Expected to find content: 'Chef Servers' within the element: <chef-breadcrumbs> but never did.
> ```
Thank you @SEAjamieD 
I have updated the PR. please have a look.

**Review by SEAjamieD — APPROVED** [review]
🎉

**Review by kalroy — APPROVED** [review]
Tested by running in local. Looks fine.

**Pull request merged**
