### PR TITLE
add docs aliases

### PR DESCRIPTION
**Pull request by susanev**
### :nut_and_bolt: Description: What code changed, and why?

Recently, I noticed the [automate section on docs.chef.io](https://docs.chef.io/#chef-automate) which listed a number of pages that 404'd, so this is adding the aliases for those pages that had their names changed at some point in the past.

### :+1: Definition of Done
less 404s

### :athletic_shoe: How to Build and Test the Change
`make serve` from `components/automate-chef-io`... but i dont think we can really test this until it merges.

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [x] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by kagarmoe** [comment]
Hi,

This is an interesting idea, but I'm not sure what problem you're trying to solve. Please open an issue describing the problem and your solution, so we can decide if this is an approach that we want to support right now.

Thanks!

**Comment by kagarmoe** [comment]
Hi,
We're fixing this on the chef-web-docs side of things, so we don't need to alias here. Going forward, please make an issue to propose changes to the frontmatter. Thanks!

**Comment by susanev** [comment]
Oh okay will do, I added other aliases a bit back and these were missed.

**Comment by susanev** [comment]
@kagarmoe An issue in the automate repo?

**Comment by kagarmoe** [comment]
Thanks for understanding!

**Comment by susanev** [comment]
closing this, issue created: https://github.com/chef/automate/issues/2778

**Pull request closed without merging**
