### PR TITLE
[pipeline] Enable EAS Dashboard in dev & acceptance envs

### PR DESCRIPTION
**Pull request by afiune**
As an EAS Team Member,I would like to have proper development & acceptance environments that deploy automatically on every merge of a PR,So I can do proper "Acceptance Demos" and verify that the functionality we are shipping is the correct one.

### :nut_and_bolt: Description

We currently don't have a place where we as a Team can demo our work that is being shipped to our customers, that is our Acceptance Environment. As well as a place where we can do Demos to the entire organization and a place where anyone outside our team can go play with the work we are doing internally within the EAS team.

We also don't have a place where we are testing upgrades, so any modification to our database schema is not currently being tested.

This card is to *create such environment(s)* and start doing acceptance of all the work we are doing in the EAS Team.

### :+1: Definition of Done
Enable the Apps Beta Feature in one of our existing instances for our Development and Acceptance environments.

After this PR is merged we will have EAS Dashboard enabled in the following instances:
- a2-perf-test-single-local-inplace-upgrade-dev.cd.chef.co
- a2-perf-test-single-local-inplace-upgrade-acceptance.cd.chef.co

### :athletic_shoe: Demo Script / Repro Steps
Merge and check the pipeline. (aka YOLO!) 😆 🚀 

### :chains: Related Resources
https://chefio.atlassian.net/browse/A2-794

### :white_check_mark: Checklist

- [ ] Necessary tests added/updated?
- [ ] Necessary docs added/updated?
- [ ] Code actually executed?
- [ ] Vetting performed (unit tests, lint, etc.)?

### CODE REVIEW

**Comment by jeremiahsnapp** [comment]
This PR looks great to me but does EAS require chef server and workflow? If it doesn't then what about just applying it to the performance instance where we have chef-load already applied?

https://github.com/chef/automate/blob/master/terraform/test-environments/scenarios/performance_test_single_local_inplace_upgrade.tf

**Comment by afiune** [comment]
@jeremiahsnapp it does not need chef-server or workflow, I enable them into those instances because we talked over Slack and those are the once you suggested 😅 -- Should I use the other one that doesn't have workflow or chef server?

**Comment by jeremiahsnapp** [comment]
Sorry about the confusion there @afiune. I misunderstood what your requirements were. It sounds like applying these changes to the performance testing instance is the better choice.

**Comment by afiune** [comment]
Will do that Jeremiah! It’s all good. Thanks for your assistance! 💯

**Comment by afiune** [comment]
@danielsdeleo I can load some data as we do in our studio but I would recommend waiting for the habitat integration to plug everything together. How does that sound?

**Comment by danielsdeleo** [comment]
> I can load some data as we do in our studio but I would recommend waiting for the habitat integration to plug everything together. How does that sound?

Sounds good to me!

**Pull request merged**
