### PR TITLE
Found the chars not allowed for passwords

### PR DESCRIPTION
**Pull request by daveaugustus**
Signed-off-by: Pappu Kumar <pappu.kumar@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
The idea was to update the documentation adding the special characters not allowed for setting passwords for OpenSearch and Postgres db.

### :+1: Definition of Done
Update the documents every where we have config.toml for OpenSearch and Postgres db config.

### :athletic_shoe: How to Build and Test the Change
Please test the changes at https://deploy-preview-7432--chef-automate.netlify.app/automate/opensearch/

https://user-images.githubusercontent.com/36985548/192173579-6287fcdf-c9f4-499c-98bf-c5c9b9d67f0d.mov

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### CODE REVIEW

**Review by punitmundra — COMMENTED** [review]
$ is also excluded

**Comment by daveaugustus** [comment]
@punitmundra  $ can be included in the password as I tried this ```user@~!@#$%^&*()``` sample password in both OpenSearch and Postgres and it worked.

**Comment by daveaugustus** [comment]
@punitmundra I have added ``` $ ``` to the md files.

**Review by Dmaddu — CHANGES_REQUESTED** [review]
The content should be displayed as a warning similar to below 

image

**Review by dishanktiwari2501 — APPROVED** [review]

**Comment by daveaugustus** [comment]
@Dmaddu @dishanktiwari2501  has updated to this
Screenshot 2022-09-27 at 4 04 52 PM

**Review by punitmundra — APPROVED** [review]

**Comment by daveaugustus** [comment]
@Dmaddu Done
Screenshot 2022-09-28 at 1 21 54 AM

**Review by Dmaddu — APPROVED** [review]

**Pull request merged**
