### PR TITLE
[infra-proxy-service] Role API uniform response objects

### PR DESCRIPTION
**Pull request by vsingh-msys**
### :nut_and_bolt: Description: What code changed, and why?

- Remove expanded run-list attributes from `GetRole` API.
- Added `GetRoleEnvironments` API to fetch the associated role environments.
- Added `GetRoleExpandedRunlist` API to fetch the expanded run list.

### :chains: Related Resources
Fixes: https://github.com/chef/automate/issues/4893

### :+1: Definition of Done
- GetRole api not returning expaded runlist attribute. 
- Infra service added with two new API `GetRoleEnvironments` & `GetRoleExapndedRunList` APIs.

### :athletic_shoe: How to Build and Test the Change

- `rebuild components/infra-proxy-service`
- `rebuild components/automate-gateway`

Steps to test:

- To add data using 3rd internal steps https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
- GetRole API

```
curl -sSkH "api-token: $(get_admin_token)" https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/roles/chef-load-role-499187700?pretty

{
  "name": "chef-load-role-499187700",
  "chef_type": "role",
  "description": "auto generated role",
  "default_attributes": "{}",
  "override_attributes": "{}",
  "json_class": "Chef::Role",
  "run_list": [
    "recipe[audit::default]",
    "recipe[chef-client::default]"
  ]
}
```

- API to fetch Role environments

```
curl -sSkH "api-token: $(get_admin_token)" https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/roles/chef-load-role-499187700/environments?pretty

{
  "environments": [
    "_default"
  ]
}
```

- API to get the expanded run list based on environment

```
curl -sSkH "api-token: $(get_admin_token)" https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/roles/chef-load-role-499187700/runlist/_default?pretty
{
  "id": "_default",
  "run_list": [
    {
      "type": "recipe",
      "name": "audit::default",
      "version": "",
      "skipped": false,
      "position": 0,
      "error": "",
      "children": [
      ]
    },
    {
      "type": "recipe",
      "name": "chef-client::default",
      "version": "",
      "skipped": false,
      "position": 0,
      "error": "",
      "children": [
      ]
    }
  ]
}

```

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by rickmarry** [comment]
In the "How to Build and Test the Change" section, you specify the role: chef-load-role-499187700, which does not exist for me when i followed the instructions.. I used one that did exist: chef-load-role-663568800 and was able to see data in the same structure as you have listed

**Review by rickmarry — APPROVED** [review]
This looks great.  thank you @vsingh-msys !

**Review by vivek-yadav — APPROVED** [review]
Looks fine to me. Approved.

**Comment by vivek-yadav** [comment]
Please resolve conflicts before merge.

**Pull request merged**
