### PR TITLE
Jamie/2890 return button

### PR DESCRIPTION
**Pull request by SEAjamieD**
### :nut_and_bolt: Description: What code changed, and why?

The API docs are on an outside site and getting back to docs was a pretty bad experience. I added a "return to docs" button on the API page. 

There are limitations to styling the API pages. Even so, this button could be prettier. 

Screen Shot 2020-02-18 at 12 33 04 PM

### :chains: Related Resources
https://github.com/chef/automate/pull/2890

### :athletic_shoe: How to Build and Test the Change

Checkout this branch
Build the API docs by running the following all-in-one command from the top-level automate directory:

```
hab studio run "source .studiorc && compile_all_protobuf_components" && pushd components/automate-chef-io/ && make sync_swagger_files generate_swagger && make serve || popd
```
Review the API docs in your browser:

http://localhost:1313/docs/api

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by SEAjamieD** [comment]
I should also mention - I did not update white space around the logo because I don't have a way to effectively target that element yet.  That will be the first piece I look for when I start researching.

**Comment by susanev** [comment]
did someone require an all caps button?
they are generally less accessible because they are more difficult to read
also, i dont think the api docs are using roboto, it seems to be montserrat

**Comment by susanev** [comment]
for the white space, we could just add it to the image i suppose if it ends up not being possible to style it.

**Comment by SEAjamieD** [comment]
> did someone require an all caps button?
> they are generally less accessible because they are more difficult to read
> also, i dont think the api docs are using roboto, it seems to be montserrat

No I didn't know of any requirements.  When I inspected the documentation for tabs for headers like "Compliance", I saw Roboto but i'll double check.  I added the all caps to try and somewhat match.

**Comment by SEAjamieD** [comment]
sorry to do this here: but i'm closing this PR in favor of https://github.com/chef/automate/pull/2902 because this had random files deleted from it and is causing buildkite failures.

**Pull request closed without merging**
