### PR TITLE
#3246 Data feed object is not updating.

### PR DESCRIPTION
**Pull request by satellite15**
The data feed updates are no longer working. See

https://github.com/chef/automate/issues/3246

for full details.

To build in the hab studio

compile_go_protobuf_component api
build components/automate-gateway
build components/data-feed-service

and deploy these components

The API response should be of the form

{
  "id": "1",
  "success": true
}

where id is the string representation of an integer and is the id of the updated datafeed object.

Signed-off-by: Martin Scott <mscott@chef.io>

### :nut_and_bolt: Description: What code changed, and why?

Resolution: UpdateDestinationRequest.Id changed to string from int64.

The string is then parsed to an int64 in the data-feed-service before the update is processed. No changes to the underlying DB code.

### :athletic_shoe: How to Build and Test the Change

Create a datafeed through the UI, edit the created data feed. The edit should be saved.

Test using the API using curl.

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated? Manual testing.
- [x] Docs added/updated? Swagger docs updated
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by vinay033** [comment]
@satellite15 
can you please mention the build steps and also what is the API response is coming when we update the feed object.

**Comment by satellite15** [comment]
> @satellite15
> can you please mention the build steps and also what is the API response is coming when we update the feed object.

I have updated the description

**Comment by vinay033** [comment]
> > @satellite15
> > can you please mention the build steps and also what is the API response is coming when we update the feed object.
> 
> I have updated the description

Can you please change the API response same as other(server, org, api-token...etc) for CREATE and UPDATE both API responses, we need all attributes. for feed we need.
```
{
  success: true
  id: "1"
  name: "feed1"
  url: "http://requestbin.sjcmmsn.com/ys9bp7ys"
  secret: "96f299bd-5224-48a5-91fb-09c2e14e5780" 
}
```

**Comment by susanev** [comment]
@satellite15 if what @vinay033 is asking for is not possible let me know and i can adjust the designs that vinay is working from.

**Comment by satellite15** [comment]
> @satellite15 if what @vinay033 is asking for is not possible let me know and i can adjust the designs that vinay is working from.

Are these responses for a UI redesign? Or just for testing?

The reason I have not included the fields for create or update in the responses is that the underlying DB library calls do not appear to return the what was inserted or updated, just the id of the inserted or updated record. Thus the id is returned and a GetDestination request with the ID will return the full details. If these are for a UI redesign I can check the DB library documentation again and see if there is an alternative approach. If this is for some testing purpose then please use the GetDestination.

Also note that we are aiming for a GA release of the data-feed-service with it's ServceNow integration for ChefConf. Once we begin service now certification for the application there will be less scope for changing the datafeed API.

**Comment by susanev** [comment]
@satellite15, @vinay033 is working on aligning the data feed ui with the rest of automate. the work is defined in https://github.com/chef/automate/issues/2098

@vinay033 could you let martin know the specific piece you are working on right now?

**Comment by satellite15** [comment]
@susanev , @vinay033 at a glance at #2098 I don't see why you would need the responses to return anything more than the ID. 

I checked the DB lib. the insert and update calls do not return what is updated, on insert I have the id is returned and on update the count of updated records returned. e.g. 1 if updated, 0 otherwise. If I amend the responses to send the url, secret then these are simply the values that are sent from the UI and if you already have them is there a need for them returned?

**Comment by vinay033** [comment]
> @satellite15, @vinay033 is working on aligning the data feed ui with the rest of automate. the work is defined in #2098
> 
> @vinay033 could you let martin know the specific piece you are working on right now?

I am working on the feed update part and delete the feed object. I will check with this response and let you know.

**Comment by vinay033** [comment]
> @susanev , @vinay033 at a glance at #2098 I don't see why you would need the responses to return anything more than the ID.
> 
> I checked the DB lib. the insert and update calls do not return what is updated, on insert I have the id is returned and on update the count of updated records returned. e.g. 1 if updated, 0 otherwise. If I amend the responses to send the url, secret then these are simply the values that are sent from the UI and if you already have them is there a need for them returned?

I worked on chef server and org modules and all the CREATE and UPDATE API response return the same as I mentioned above, also I have checked other module API responses so I specified.

**Comment by vinay033** [comment]
@satellite15 
I will check with the new changes response and let you know.

**Comment by vinay033** [comment]
Thanks @satellite15 ,  Thanks for the quick fix.

**Pull request merged**
