### PR TITLE
Added dropdown for fqdn and ip address.

### PR DESCRIPTION
**Pull request by himanshi-chhabra**
Signed-off-by: Himanshi Chhabra <hchhabra@progress.com>

### :nut_and_bolt: Description: What code changed, and why?
We currently require both the FQDN and the IP address of the chef server. We need to change and make it optional so add a dropdown in which the user can select any option of FQDN or IP address

### :chains: Related Resources
#4945 #4998 

### :+1: Definition of Done
 Added a dropdown in which the user can select any option of FQDN or IP address
### :athletic_shoe: How to Build and Test the Change

```
STEP 1
inside the hab studio

[default:/src:0]# build components/automate-ui-devproxy/
[default:/src:0]# start_automate_ui_background
[default:/src:0]# start_all_services

STEP 2
open new window
go to automate UI path

$ cd components/automate-ui
and run the command 

npm run serve:hab
```
To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
Steps for policy file  tab: 
1. Go To  Infrastructure -> Chef Servers -> click Add chef server -> Add name -> Select FQDN or IP Address option -> Add FQDN or IP Adress form filed data -> click Add chef server

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

Chef-Automate (1)

### CODE REVIEW

**Comment by chaitali-mane** [comment]
Space between 'Type' and dropdown must be less.
space

**Comment by chaitali-mane** [comment]
If I select IP Adress and I cancel/ close modal and open again then the dropdown value is IP Adress. Same for the FQDN. Can dropdown be set to the default value?

**Review by vinay033 — APPROVED** [review]

**Comment by chaitali-mane** [comment]
fqdn-err
I have some observations
1. Font weight of dropdown must be normal.
2. space between dropdown and below test should be more.
3. height of dropdown should be the same

**Comment by chaitali-mane** [comment]
If there is no data available for FQDN or IP Address then can we show '-' instead of empty?

**Review by chaitali-mane — APPROVED** [review]
Working as expected

**Pull request merged**
