### PR TITLE
Automate-3144 API compliance reports node filters

### PR DESCRIPTION
**Pull request by tarablack01**
### :nut_and_bolt: Description: What code changed, and why?
When I looked into this, I realized the UI is doing the status filtering (https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.ts#L64).

Filtering by status is supported by backend, and won't result in results being spread across pages, so let's just move to status filtering via api.

### :chains: Related Resources
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/3144

### :+1: Definition of Done
Filtering by status is filtering via api.

### :athletic_shoe: How to Build and Test the Change
hab studio enter
export DEVPROXY_URL=localhost
build components/automate-ui-devproxy
start_automate_ui_background
start_all_services
chef_load_nodes

### :white_check_mark: Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Screen Shot 2020-05-13 at 11 41 20 AM
Screen Shot 2020-05-13 at 11 41 35 AM

### CODE REVIEW

**Comment by tarablack01** [comment]
@vjeffrey thanks for finding that and also requesting UX team verify the desired result. I know why this is happening as all the filters are processed through the parent reporting component. If this needs to be changed, I can do that. 😊

**Comment by susanev** [comment]
good catch! summary data should not change based on the filters. the filters appear below the summary and within the tabs. so visually folks will not expect the summary data to change as they adjust the filters.

**Comment by jonong1972** [comment]
Yeah this is wonky.  I think I understand the reason why the system is doing what its doing.  If I recall correctly the search was built as if a user were to search on something, that would affect the status?  For instance, show me all nodes with Control X, and then reflect status of nodes based on Control X - which then would update the Summary?  I could be wrong though.

**Comment by tarablack01** [comment]
@vjeffrey @susanev @jonong1972 Fixed filtering to be only nodes.

**Comment by susanev** [comment]
cool thank you!! i think this pr now addresses #3674 too
noticed that when navigating between the tabs that the filters persist, is this what you want @jonong1972?

**Comment by jonong1972** [comment]
@susanev yes. would be great it would persist. But I think in order for that to happen for each respective tab we would probably have to change the query param from something like. "?status=failed" to "?node_status=failed", "?profile_status=failed"

**Comment by tarablack01** [comment]
@jonong1972 @susanev the status will persist. We just need to hook up profiles with api status filtering. 😊

**Pull request merged**
