### PR TITLE
added changes to show the inspec version on node details page

### PR DESCRIPTION
**Pull request by vinay033**
Signed-off-by: vinay033 <vsharma@chef.io>

### :nut_and_bolt: Description
add inspec version to node details page
### :chains: Related Resources
https://github.com/chef/automate/issues/156

###  Expected UI
Screenshot from 2019-05-07 12-02-25

### CODE REVIEW

**Comment by vjeffrey** [comment]
hey @vinay033 thank you so much for jumping on this one!
would you mind including a screenshot of what it looks like with the changes to make it easier for ppl to review without pulling down the changes?

**Comment by vinay033** [comment]
> hey @vinay033 thank you so much for jumping on this one!
> would you mind including a screenshot of what it looks like with the changes to make it easier for ppl to review without pulling down the changes?

sure I will add the screenshot.

**Comment by vinay033** [comment]
> hey @vinay033 thank you so much for jumping on this one!
> would you mind including a screenshot of what it looks like with the changes to make it easier for ppl to review without pulling down the changes?

I attached the screenshot, please check.

**Comment by alexpop** [comment]
Screen Shot 2019-05-07 at 10 36 03 AM

Thank you @vinay033. Change looks good. 
@jonong1972 can you confirm the `chef-icon` that should prefix the `InSpec Version` label? Vinay used the `public` chef-icon, same as Environment, but just want to confirm with you.

**Comment by jonong1972** [comment]
@alexpop , @vinay033 
Funny you should bring this up. I am working on new designs and to be consistent across the Automate system, the new designs actually removed all those icons.  Would be sweet if we can do this now?

**Comment by susanev** [comment]
should we update the two screenshots towards the bottom of the compliance docs page? https://automate.chef.io/docs/compliance/#scan-history

**Comment by alexpop** [comment]
Sounds like a plan Jon. Thank you Susan, let's update the screenshots after we remove the icons.

**Comment by alexpop** [comment]
@jonong1972 should the icons in the Report Metadata go away as well?

https://automate.chef.io/docs/compliance/#compliance-status-and-report-metadata

**Comment by vinay033** [comment]
> Very good work Vinay.
> I'll talk with Jon today and open a ticket for the removal of the other icons.
> Thank you!

Thank you so much @alexpop :)

**Pull request merged**
