### PR TITLE
bump lib/pq to 1.2.0

### PR DESCRIPTION
**Pull request by stevendanna**
Full set of changes:

https://github.com/lib/pq/compare/83612a56d3dd...3427c32cb71afc948325f299f040e53c1dd78979

Highlights include:

- A fix for a potential deadlock when related to commit and rollback
- QuoteLiteral function that can replace our custom implementation

Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by stevendanna** [comment]
This appears to be hitting this:  https://github.com/lib/pq/issues/870

Namely, if HAProxy times out our db connection before at the wrong time, we can get a broken pipe write error that we didn't before. We'll have to sort out what we want to do here.

**Comment by phiggins** [comment]
There's some similar looking quoting code in here: https://github.com/chef/automate/blob/master/lib/pgutils/pgutils.go

**Comment by vjeffrey** [comment]
can we close this, since we did the lib/pq thing?

**Comment by stevendanna** [comment]
Yup! Thanks @danielsdeleo

**Pull request closed without merging**
