### PR TITLE
Data bag details UI improvements changes with search box

### PR DESCRIPTION
**Pull request by vinay033**
### :nut_and_bolt: Description: What code changed, and why?
Need to update the new UI for the data bags details page with the search bar.
UX design
data-bag-search

### :chains: Related Resources
https://github.com/chef/automate/issues/4620
https://github.com/chef/automate/issues/4670
### :+1: Definition of Done
I have added new UI changes for the data bag details page using the search bar.
### :athletic_shoe: How to Build and Test the Change
```
STEP 1
inside the hab studio

[default:/src:0]# build components/automate-ui-devproxy/
[default:/src:0]# start_automate_ui_background
[default:/src:0]# start_all_services

STEP 2
open new window
go to automate UI path

$ cd components/automate-ui
and run the command 

npm run serve:hab

To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
Go to Infrastructure tab >> Chef Servers it's under Chef-Server feature flag  >> click to any server >> see the list of org's >> click to any org >> on org details page you can see the multiple tabs >> click to data bags tabs >> you can see the list of data bags >> after click you can see the data bag details page.
```
### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
data-bag-new-search

### CODE REVIEW

**Review by shaik80 — DISMISSED** [review]

**Review by vivekshankar1 — CHANGES_REQUESTED** [review]
Thanks vinay,
The details are being fetched properly.
There are some issues i found:

- The search button icon is not centered properly. There is also a bit of extra space to the right. Can you also take a look at the fonts and colors if they match the ux

Screenshot 2021-02-15 at 7 46 26 PM

- Also there is some unexpected behaviour in the search action. If we do a search query and then delete the query from the input box the search result is not fetching all the data.

**Comment by vinay033** [comment]
> Thanks vinay,
> The details are being fetched properly.
> There are some issues i found:
> 
> * The search button icon is not centered properly. There is also a bit of extra space to the right. Can you also take a look at the fonts and colors if they match the ux
> 
> Screenshot 2021-02-15 at 7 46 26 PM
> 
> * Also there is some unexpected behaviour in the search action. If we do a search query and then delete the query from the input box the search result is not fetching all the data.

I have updated the changes.. can you please check.

**Review by vivekshankar1 — APPROVED** [review]
Thanks @vinay033 . The ui is approved and the search is working fine.

**Review by shaik80 — APPROVED** [review]

**Comment by chaitali-mane** [comment]
While testing found list caption spacing changes and title active state CSS changes.

**Comment by chaitali-mane** [comment]
Created issue for the UI chages #4750 and raised PR with changes #4754 against issue.

**Pull request merged**
