### PR TITLE
test: use `T.TempDir` to create temporary test directory

### PR DESCRIPTION
**Pull request by Juneezee**
### :nut_and_bolt: Description: What code changed, and why?

A testing cleanup. This PR replaces `ioutil.TempDir` with `t.TempDir` in tests.

We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.

### :chains: Related Resources

Reference: https://pkg.go.dev/testing#T.TempDir

### :+1: Definition of Done

No leftover temporary directories after the tests have finished. This should be done automatically by `T.TempDir` unless an error occurred while removing the directory.

### :athletic_shoe: How to Build and Test the Change

Run Go tests

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### CODE REVIEW

**Comment by vivekshankar1** [comment]
There are few other references too for `ioutil.TempDir` in few other files, can we also change those as well ?

**Comment by Juneezee** [comment]
> Thanks for the pr @Juneezee, There are few other references too for `ioutil.TempDir` in few other files, can we also change those as well ?

@vivekshankar1 Thanks for reviewing this PR. I did a search on the whole project but I don't think there are still other `ioutil.TempDir` that we can change (?)
image

If you are referring to those `ioutil.TempDir` in non `*_test.go` files then we can't change it. `t.TempDir` is only available in the `testing` package.

**Comment by vivekshankar1** [comment]
> > Thanks for the pr @Juneezee, There are few other references too for `ioutil.TempDir` in few other files, can we also change those as well ?
> 
> @vivekshankar1 Thanks for reviewing this PR. I did a search on the whole project but I don't think there are still other `ioutil.TempDir` that we can change (?) image
> 
> If you are referring to those `ioutil.TempDir` in non `*_test.go` files then we can't change it. `t.TempDir` is only available in the `testing` package.

Thanks all looks good, can you check if below line is required:
https://github.com/chef/automate/blob/89b28025615dcbc9aa0f67bf5f7dce90a095c8dd/components/automate-deployment/pkg/a1upgrade/a1upgrade_compat_test.go#L209

**Comment by Juneezee** [comment]
> > > Thanks for the pr @Juneezee, There are few other references too for `ioutil.TempDir` in few other files, can we also change those as well ?
> > 
> > 
> > @vivekshankar1 Thanks for reviewing this PR. I did a search on the whole project but I don't think there are still other `ioutil.TempDir` that we can change (?) image
> > If you are referring to those `ioutil.TempDir` in non `*_test.go` files then we can't change it. `t.TempDir` is only available in the `testing` package.
> 
> Thanks all looks good, can you check if below line is required:
> 
> https://github.com/chef/automate/blob/89b28025615dcbc9aa0f67bf5f7dce90a095c8dd/components/automate-deployment/pkg/a1upgrade/a1upgrade_compat_test.go#L209

@vivekshankar1 Yes, that line is required and cannot be replaced by `t.TempDir` because `t.TempDir` doesn't allow you to specify a parent directory for the tempdir.

**Review by vivekshankar1 — APPROVED** [review]

**Pull request merged**
