### PR TITLE
Enable protobuf breaking change detection

### PR DESCRIPTION
**Pull request by danielsdeleo**
### :nut_and_bolt: Description: What code changed, and why?

Enables the breaking change detector for protobufs 🎉 

For now, the guidance if we need to sneak a change past is to configure that file as ignored and then revert the config in a later PR.

### :chains: Related Resources

buf's docs:
* https://buf.build/docs/breaking-overview
* https://buf.build/docs/breaking-configuration
* https://buf.build/docs/breaking-checkers

### :+1: Definition of Done

Breaking change fails in Ci. I'll make a demo PR of this soon. Locally, you can try making breaking changes in api/external protos and `compile_all_protobuf_components` should fail.

### CODE REVIEW

**Comment by lancewf** [comment]
I am getting errors when I try to run the `check_breaking_for_all_proto_components` command. 

The first time I got the below error
```
github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
bash: git: command not found
🔎 Checking protos for breaking changes with `buf check breaking --against-input .git#branch=master`...
input: timed out after 34035 files: context deadline exceeded
🚨 Command `buf check breaking --against-input .git#branch=master` failed! Refer to the docs if you need help fixing:
- https://buf.build/docs/breaking-overview
- https://buf.build/docs/breaking-checkers
- https://buf.build/docs/breaking-configuration

See also the config file `buf.yaml` in the repo root
🚨🚨🚨 If you NEED to get a breaking change through Ci: 🚨🚨🚨
add your file to the ignored files in buf.yaml and remove it in a subsequent pull request
```
Then I installed git with `install_if_missing core/git git` and ran the command again and got the below error. 

```
[6][default:/src:0]# check_breaking_for_all_proto_components
GEN: api/external/annotations/iam/*.proto
/src/components /src
GEN: components/automate-grpc/protoc-gen-a2-config/api/a2conf/*.proto
/src
🔎 Checking protos for breaking changes with `buf check breaking --against-input .git#branch=master`...
input: timed out after 27811 files: context deadline exceeded
🚨 Command `buf check breaking --against-input .git#branch=master` failed! Refer to the docs if you need help fixing:
- https://buf.build/docs/breaking-overview
- https://buf.build/docs/breaking-checkers
- https://buf.build/docs/breaking-configuration

See also the config file `buf.yaml` in the repo root
🚨🚨🚨 If you NEED to get a breaking change through Ci: 🚨🚨🚨
add your file to the ignored files in buf.yaml and remove it in a subsequent pull request
```

I got a similar error when running `lint_all_protobuf_components`
```
[7][default:/src:1]# lint_all_protobuf_components
GEN: api/external/annotations/iam/*.proto
/src/components /src
GEN: components/automate-grpc/protoc-gen-a2-config/api/a2conf/*.proto
/src
🧹 Linting protos with `buf check lint`...
input: timed out after 26563 files: context deadline exceeded
😱 Command `buf check lint` failed! Refer to the docs if you need help fixing:
- https://buf.build/docs/style-guide/
- https://buf.build/docs/lint-checkers
- https://buf.build/docs/lint-configuration

See also the config file `buf.yaml` in the repo root
```
I am not sure what I am doing wrong.

**Review by srenatus — APPROVED** [review]
Thank you! 🚀

**Comment by danielsdeleo** [comment]
@lancewf Since the linter is already in, I'm gonna merge this since it won't make anything worse. I can try to help troubleshoot whenever you're free. Probably one large difference in our environments is I'm running docker Mac "edge" channel. They've been experimenting with different approaches to speeding up the shared filesystems. It's still not _fast fast_ but it's better. If you need to compile some protos locally and don't want to deal with `buf`, you can use `compile_all_protobuf_components_nolint`

**Comment by danielsdeleo** [comment]
Confirmed that this works as expected in Ci in PR https://github.com/chef/automate/pull/4305 - https://buildkite.com/chef-oss/chef-automate-master-verify/builds/13848#a7e7fdcc-5b3b-4dbe-be45-ab7210f8b6cd

**Pull request merged**
