### PR TITLE
trigger rebuilds for core/nginx/1.17.3

### PR DESCRIPTION
**Pull request by srenatus**
For #1245.

### CODE REVIEW

**Comment by srenatus** [comment]
@stevendanna what do you think? to pin or not to pin? 🤔 I'm not happy about this, but it's an easy rebuild 😄

**Comment by stevendanna** [comment]
I suppose we could merge this and then immediately merge something that unpins us :D

Since automate-workflow-web is building again, another option would be to trigger a full rebuild in buildkite.  Between the grpc update, the golang update, and I'm sure some others, my guess is we are gonna be close to a full rebuild for the next release anyway.

**Comment by srenatus** [comment]
@stevendanna I agree, it's a bit silly to avoid the full rebuild at this point. Can kick it off tomorrow morning to have the US night for dealing with unexpected issues...

**Comment by srenatus** [comment]
✔️ we've rebuilt all hartifacts using the pipeline.

**Pull request closed without merging**
