### PR TITLE
compliance-service: fix nil pointer dereference

### PR DESCRIPTION
**Pull request by stevendanna**
We recently observed the following panic during a CI failure:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xffaeab]

    goroutine 2840 [running]:
    github.com/chef/automate/components/compliance-service/ingest/ingestic.(*ESClient).UpdateReportProjectsTags(0xc0000b3cf0, 0x161b660, 0xc0096e22c0, 0xc00b3f8180, 0x1, 0x161b660, 0xc0096e22c0, 0x141ef5e)
            /src/components/compliance-service/ingest/ingestic/ingestic.go:350 +0x4ab
    github.com/chef/automate/components/compliance-service/ingest/ingestic.(*ESClient).UpdateProjectTags(0xc0000b3cf0, 0x161b660, 0xc0096e22c0, 0xc00b3f8180, 0x0, 0x0, 0x0, 0xc00b40e420, 0x0)
            /src/components/compliance-service/ingest/ingestic/ingestic.go:197 +0xbb
    github.com/chef/automate/lib/authz.(*ESStartProjectTagUpdaterTask).startProjectTagUpdater(0xc0002b4520, 0x161b660, 0xc0096e22c0, 0xccf9070573, 0x282f66e9, 0x282f66e900000000, 0x5dd50328, 0xc00b4b7560)
            /src/lib/authz/project_rules_update_workflow.go:221 +0x138
    github.com/chef/automate/lib/authz.(*ESStartProjectTagUpdaterTask).Run(0xc0002b4520, 0x161b660, 0xc0096e22c0, 0x15f5220, 0xc00b40e300, 0x3c, 0xc003e38a40, 0x1f, 0xd0)
            /src/lib/authz/project_rules_update_workflow.go:202 +0x46
    github.com/chef/automate/lib/cereal.(*registeredExecutor).runTask(0xc0000d9380, 0x161b660, 0xc0096e22c0, 0xc00b40e300, 0x1612c20, 0xc00b40e2d0, 0x1, 0xc00b40e2d0)
            /src/lib/cereal/cereal.go:911 +0xaa
    github.com/chef/automate/lib/cereal.(*registeredExecutor).startTaskWorker.func1(0xc0003e4000, 0x15f5240, 0xc000510230, 0x161b660, 0xc0000ae780, 0xc0000d9380, 0xc0001a4060)
            /src/lib/cereal/cereal.go:902 +0xdb
    created by github.com/chef/automate/lib/cereal.(*registeredExecutor).startTaskWorker
            /src/lib/cereal/cereal.go:873 +0x298

Unfortunately, the logs don't indicate what the underlying error was,
but this change hopefully fixes the most proximate cause of the panic:
on error, the result from the elastic library may be nil.

Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by stevendanna** [comment]
@vjeffrey 🤦‍♂ I didn't even think to search for more uses of this pattern.  I'll push some fixes for these:

```
 > rg 'return startTaskResult.TaskId'
components/compliance-service/ingest/ingestic/ingestic.go
350:	return startTaskResult.TaskId, err
490:	return startTaskResult.TaskId, err

components/event-feed-service/pkg/persistence/feed-elastic.go
60:	return startTaskResult.TaskId, err

components/ingest-service/backend/elastic/actions.go
88:	return startTaskResult.TaskId, err

components/ingest-service/backend/elastic/elastic.go
346:	return startTaskResult.TaskId, err

components/ingest-service/backend/elastic/nodes.go
230:	return startTaskResult.TaskId, err
```

**Comment by stevendanna** [comment]
pushed a commit for more sites I found via grep

**Comment by phiggins** [comment]
Sorry for the random question, but this seems like something the go compiler or the linter could help us with. Is there a linter we haven't turned on for this?

**Comment by stevendanna** [comment]
@phiggins Good question, I don't know off hand but I'll look into this.

**Pull request merged**
