### PR TITLE
include waived status, justification, and expiration date on csv export

### PR DESCRIPTION
**Pull request by vjeffrey**
Signed-off-by: Victoria Jeffrey <vjeffrey@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
include waived status, justification, and exp date on csv

### :chains: Related Resources
https://github.com/chef/automate/issues/3853

### :+1: Definition of Done
waiver info in the csv report

### :athletic_shoe: How to Build and Test the Change
rebuild compliance
load_compliance_reports
download csv report, see waiver data

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] Tests added/updated?
- [n/a] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by vjeffrey** [comment]
> the JSON is added by default?

im gonna go double check, but im pretty sure it's already added - bc we return the full report and this information is already on the full report to be able to display in ui

**Comment by srenatus** [comment]
❓ Do we care for compatibility here? Something written against the JSON export probably would just ignore extra fields, tools consuming CSV might choke on the new columns...

**Comment by vjeffrey** [comment]
> tools consuming CSV might choke on the new columns

do you mean if someone has built something themselves around the expected format of our csv export?

**Comment by srenatus** [comment]
@vjeffrey yup, that possibility.

**Comment by vjeffrey** [comment]
hmmm. i don't know that we've ever promised compatibility on the csv reports -- i'm not sure how we could support that? do you have an idea in mind @srenatus ?

**Comment by srenatus** [comment]
Oh I was just wondering. Let's call it out in the release notes so people aren't caught by surprise, maybe?

If we wanted to do that, we'd have versioned endpoints as one possibility. Not a small fix, though, I guess. Or have the client pass in a list of desired columns, defaulting to the set we had before.

**Comment by vjeffrey** [comment]
i would love to one day change our apis so that more of them accept "desired fields returned" kinda thing, i opened an issue about that a while ago: https://github.com/chef/automate/issues/2147. but ya - bigger change. one day! 🤞

**Pull request merged**
