### PR TITLE
updated pr template

### PR DESCRIPTION
**Pull request by vjeffrey**
### :nut_and_bolt: Description
A quick pr template update to encourage more detailed pr documentation

### :+1: Definition of Done
New pr template

### CODE REVIEW

**Comment by srenatus** [comment]
> I can see an argument for removing "vetting performed" because those are done for you in the PR, at a minimum. But I would really, really like to keep "Code actually executed?"

@msorens Would you mind stating **your argument** for _really, really_ wanting to keep this? I'm not sure I can see the need.

**Comment by msorens** [comment]
@srenatus To me, it is on par with asking "did you add tests? did you add docs?" And "did you run your code?". Failure to add a test may let some broken code get merged. Similarly, failure to actually run your code might also let some broken code get merged.

**Comment by srenatus** [comment]
> To me, it is on par with asking "did you add tests? did you add docs?"

That's interesting. I guess to me, it is not. _"Did you add tests? did you add docs?"_ are well-meaning hints about things you can easily forget in the heat of the moment. _"Did you execute your code?"_ carries a conotation of **assumed negligence**. That's not a thing I want to accept as default stance towards each other.

(Besides that, I'd say having added tests implies having executed your code, so it is also redundant. Assuming we strive for having checked boxes there.)

I'm not blocking this, just raising a concern. Maybe we should have a poll in #a2-team? 😉

**Comment by vjeffrey** [comment]
> carries a connotation of assumed negligence

that's definitely the other reason i removed the "actually" in that phrase

i'm up for doing a poll in a2-team!

**Comment by vjeffrey** [comment]
poll created! https://chefio.slack.com/archives/C6JED4R8W/p1563980057072700

**Comment by vjeffrey** [comment]
Screen Shot 2019-07-25 at 13 13 40

**Pull request merged**
