### PR TITLE
Link to builder for applications tab

### LINKED ISSUE #2417: Link Between Automate Apps Tab and the Depot
## User Story

As a user of the Automate-deployed On-Prem Habitat Depot, I'd like to be able to reach the Depot user interface without knowing the specific link. I'd like to be able to visit my Automate UI and be shown a link to the Depot.

As a benefit to Chef, by putting the link to the Depot inside the Applications tab, we'll be able to show Habitat users the functionality that is enabled when they connect their supervisors to Automate.

## Definition of Done

* Link to Builder is in the Apps tab as shown in the mockup
* If Builder is not deployed, link to the SaaS depot

## Resources

* [Invision Mockup](https://chef.invisionapp.com/share/62UZ4YG3VPJ#/screens/394830697_applications-Service_Groups-Builder_Link-Active)
* [Recording](https://drive.google.com/open?id=1Qf8zbxLr__pLol8gBcCJEzOcFYfmpb49)
* Icons come from our Material icon set and are `build` (the wrench) and `open-in-new` (the link). @apriofrost can help if needed here.

## Notes and Considerations

* Apps Tab Beta: currently the Apps tab is in Beta. It's intended to go GA soon, but we will potentially have a timing issue between when this work is ready and when the Apps tab is no longer hidden behind a feature flag. We should coordinate with @danielsdeleo on the timing here.

### PR DESCRIPTION
**Pull request by jaym**
## Overview
This change adds a new configuration lifecycle method: ConfigureProducts
where a service can do things with the products that are deployed

load balancer uses this to render a script with the deployed products

The UI reads this script, and uses that to figure out what to render for
the link. If builder is deployed, we link to the internal builder.
Otherwise, we link to bldr.habitat.sh

image

closes #2417

## Repro steps
- `rebuild automate-load-balancer`
- `automate-ui`
- `deployment-service`
- turn on ui features flag by typing `feat` in the ui and turning on applications

### CODE REVIEW

**Comment by apriofrost** [comment]
Hi @jaym , thanks for working on this! It looks great overall. 
I have one suggestion: based on the screenshot, I noticed there is a slight vertical misalignment with the "open in new tab" icon. I created a "before" and "after" screenshot to show the difference (the red lines are just to highlight the difference in alignment, they should not be included in the actual UI). 
It looks to me that currently the icon is aligned to the top of the label. Ideally, it should align to the center vertically. Let me know if it's not clear.
image

**Comment by SEAjamieD** [comment]
@jaym - How do we build this to test the change?  I'm not seeing an applications tab, so I'm thinking I need to do something other than `build components/automate-ui-devproxy`

Thanks!

**Comment by jaym** [comment]
rebuild automate-load-balancer, automate-ui, deployment-service. You'll need to enable applications after that: i think just typing in feat into the UI will give you that option

**Comment by susanev** [comment]
@SEAjamieD to see the applications tab, you need to type `feat` in the ui and turn on the applications feature flag.

**Comment by SEAjamieD** [comment]
for whatever reason, the sidebar is permanently stuck open for me, I believe this is something to do with my reproduction steps though - not your branch.  

Screen Shot 2019-12-09 at 2 05 05 PM

**Comment by susanev** [comment]
@SEAjamieD the side bar on applications is always open, it uses a different design pattern. if you want to put fake data in there you can use `applications-populate-database`

**Comment by jaym** [comment]
@apriofrost 
image

**Pull request merged**
