### PR TITLE
Return to docs button for API docs

### PR DESCRIPTION
**Pull request by kagarmoe**
Signed-off-by: kagarmoe <kgarmoe@chef.io>

### :nut_and_bolt: Description: What code changed, and why?

The API docs are on an outside site and getting back to docs was a pretty bad experience. I added a "return to docs" button on the API page. 

There are limitations to styling the API pages. Even so, this button could be prettier. 

Screen Shot 2020-02-17 at 7 33 11 PM

### :athletic_shoe: How to Build and Test the Change

Checkout this branch
Build the API docs by running the following all-in-one command from the top-level automate directory:

```
hab studio run "source .studiorc && compile_all_protobuf_components" && pushd components/automate-chef-io/ && make sync_swagger_files generate_swagger && make serve || popd
```
Review the API docs in your browser:

http://localhost:1313/docs/api

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by susanev** [comment]
for accessibility reasons, this needs to be an anchor and not a button. Ideally, it could also be styled as a link and not a button. happy to help if you would like some ux design support for this.

**Comment by kagarmoe** [comment]
Styling has to be inline. Feel free to add your changes.

**Comment by SEAjamieD** [comment]
@susanev if you want to whip up a quick button design I’m happy to pop this in today and make sure it’s accessible/styled

**Comment by susanev** [comment]
@SEAjamieD @kagarmoe heres my recommendation, if this doesnt work for yall, then changining to anchor and leaving styles as is is fine.

@SEAjamieD while you're here can you please add some white space around that chef automate logo, thank you!!

return-to-docs

**Comment by kagarmoe** [comment]
Cool! +1 on adding whitespace @SEAjamie--please!

**Comment by SEAjamieD** [comment]
I cut a branch from yours @kagarmoe so that I could separate them and opened a PR here:
https://github.com/chef/automate/pull/2901

@susanev I really didn't do much, just styled a little differently.  I understand now what @kagarmoe is saying about limited stying.  I'd suggest (if everyone is ok with it) to decide exactly how you want _only_ the button styled for now and we merge that.

I'll commit to researching how much more we can do with the styling of the layout etc.  I read that we can overwrite CSS by using more specific selectors but that needs to happen in the theme folder and I'm not ready to make changes there until I understand how redocs works.

**Comment by SEAjamieD** [comment]
closed in favor of https://github.com/chef/automate/pull/2902

**Pull request closed without merging**
