### PR TITLE
Azure feedback for Automate HA  Deployment - phase 1

### PR DESCRIPTION
**Pull request by punitmundra**
### :nut_and_bolt: Description: What code changed, and why?

https://progresssoftware.atlassian.net/browse/CHEF-14792

### :white_check_mark: Checklist

**All PRs** must tick these:

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [ ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### CODE REVIEW

**Review by dishanktiwari2501 — APPROVED** [review]

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha/#chef-automate-ha-architecture-for-onpremise--aws-non-managed

I would recommend to change aws to cloud

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_on_premises_deployment_prerequisites/#chef-automate-architecture

You can deploy a Chef Automate high availability cluster on AWS or Google Cloud Platform (GCP) VMs.

I would suggest adding "Azure" in this line above.

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_backup_restore/#backup-types

I would suggest writing a paragraph for Azure and GCP under the backup types section.

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_automate_to_automate_ha/#migration-with-filesystem-backup-via-volume-mount

I would suggest making "AWS HA deployment" some level of cloud agnostics.

Follow the steps below when migrating to On-Premises or AWS HA deployment (but not for AWS with managed services).

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_disaster_recovery_setup/#requirements

I would suggest adding some references for Azure file share in the line below.

Network accessible storage (NAS), object store (S3,MinIO,Google Cloud Storage), available in both data centers/regions

**Comment by balkarsinghkang** [comment]
https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_faqs/#what-are-different-ways-to-provision-an-on-premises-deployment

I would recommend updating the answer of above question.

**Comment by punitmundra** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_backup_restore/#backup-types

As we mention that it is a onpremise type of deployment [https://deploy-preview-8592--chef-automate.netlify.app/automate/ha/#cloud-deployment-using-azure]

so it implied that, the backup options are same as onprem type. i.e we have not written any thing extra on top of that.

**Comment by punitmundra** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_disaster_recovery_setup/#requirements
> 
> I would suggest adding some references for Azure file share in the line below.
> 
> Network accessible storage (NAS), object store (S3,MinIO,Google Cloud Storage), available in both data centers/regions

cloud specific documentation will be obsolete eventually and maintain will be a challenge, that is the reason we are not adding specific to that.

**Comment by vivekshankar1** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_on_premises_deployment_prerequisites/#chef-automate-architecture
> 
> You can deploy a Chef Automate high availability cluster on AWS or Google Cloud Platform (GCP) VMs.
> 
> I would suggest adding "Azure" in this line above.

Resolved

**Comment by vivekshankar1** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_automate_to_automate_ha/#migration-with-filesystem-backup-via-volume-mount
> 
> I would suggest making "AWS HA deployment" some level of cloud agnostics.
> 
> Follow the steps below when migrating to On-Premises or AWS HA deployment (but not for AWS with managed services).

Resolved

**Comment by vivekshankar1** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_disaster_recovery_setup/#requirements
> 
> I would suggest adding some references for Azure file share in the line below.
> 
> Network accessible storage (NAS), object store (S3,MinIO,Google Cloud Storage), available in both data centers/regions

Resolved

**Comment by vivekshankar1** [comment]
> https://deploy-preview-8592--chef-automate.netlify.app/automate/ha_faqs/#what-are-different-ways-to-provision-an-on-premises-deployment
> 
> I would recommend updating the answer of above question.

Resolved

**Pull request merged**
