### PR TITLE
Environment list search bar

### PR DESCRIPTION
**Pull request by chaitali-mane**
Signed-off-by: chaitali-mane <cmane@msystechnologies.com>

### :nut_and_bolt: Description: What code changed, and why?
Need to add the search bar for Environments List

### :chains: Related Resources
[#4668](https://github.com/chef/automate/issues/4668)

### :+1: Definition of Done
I have added the search bar for Environments list.

### :athletic_shoe: How to Build and Test the Change
if you have sample data for the infra servers than
go to >> infrastructure tab >> click on Chef server on left side navigation bar >> Organizations >> Environments tab >> see the list of Environments.

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Environments search
env-seach

Environments search value
env-search-working

No data found in Environments search
env-search-no-data

### CODE REVIEW

**Review by rickmarry — COMMENTED** [review]
how is this different than pr https://github.com/chef/automate/pull/4705?

**Review by rickmarry — APPROVED** [review]
looks good.. thank you!

**Comment by chaitali-mane** [comment]
Found some Styling issue in testing like spinner not displaying for full page height and more list header spacing.

**Comment by chaitali-mane** [comment]
Created issue for the UI chages #https://github.com/chef/automate/issues/4750 and raised PR with changes #https://github.com/chef/automate/pull/4754 against issue.

**Pull request merged**
