### PR TITLE
Fix broken link to Knife setup docs

### PR DESCRIPTION
**Pull request by ChefAustin**
This page's link to the knife setup docs is currently broken. I took a random guess at where it should be linking to so feel free to correct me if this is incorrect.

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by mjingle** [comment]
Hi @ChefAustin! Thank you for noticing this link issue and submitting a PR to fix this. Could you please add a DCO to your commit? We can't merge until this PR has a DCO. See: https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/ 

Let me know if I can help at all!

**Comment by ChefAustin** [comment]
> Hi @ChefAustin! Thank you for noticing this link issue and submitting a PR to fix this. Could you please add a DCO to your commit? We can't merge until this PR has a DCO. See: https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/
> 
> Let me know if I can help at all!

Fixed (I think), @mjingle.

**Comment by mjingle** [comment]
Hi @ChefAustin, this PR is currently blocked in the pipeline as this PR needs to be rebased. The pipeline fix was merged yesterday, so you should be golden after this rebase. Thank you for your patience while we had sorted this out.

**Review by mjingle — APPROVED** [review]
@ChefAustin Thank you for spotting and submitting these link fixes! I finally figured out what was blocking the pipeline and we're merging this!

**Pull request merged**
