### PR TITLE
Remove non async reindexes

### PR DESCRIPTION
**Pull request by lancewf**
### :nut_and_bolt: Description: What code changed, and why?
All Elasticsearch reindexes should be done with async. This change is needed because all elasticsearch requests go through the automate-es-gateway which adds a 60-second timeout.

### :chains: Related Resources

https://github.com/chef/automate/pull/1177

### CODE REVIEW

**Comment by lancewf** [comment]
I am having problems with the tests. I am not sure why it is failing. 
```
time="2019-08-06T23:51:49Z" level=debug msg="es6 incompatible other a1 index" es-created-version=2040199 index-name=.automate
--
  | Reindexing 100 insights indices for Elasticsearch 6 compatibility
  | 0 / 100    0.00%time="2019-08-06T23:51:49Z" level=info msg="migrating insights index" index-name=insights-2018.04.26
  | 0 / 100    0.00%[test harness] Received non-matching request &{GET /elasticsearch/_tasks/ HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[gzip] Content-Type:[application/json] User-Agent:[elastic/6.2.16 (linux-amd64)]] {} <nil> 0 [] false localhost:8080 map[] map[] <nil> map[] [::1]:44796 /elasticsearch/_tasks/ <nil> <nil> <nil> 0xc0000833c0}
  | http: panic serving [::1]:44796: oops
  | goroutine 238 [running]:
  | net/http.(*conn).serve.func1(0xc0000381e0)
  | /usr/local/go/src/net/http/server.go:1769 +0xc9
  | panic(0x101a3e0, 0x1472090)
  | /usr/local/go/src/runtime/panic.go:522 +0x1b5
  | github.com/chef/automate/components/automate-deployment/pkg/a1stub.debug404Handler(0x14b9de0, 0xc00016e000, 0xc0000ae100)
  | /go/src/github.com/chef/automate/components/automate-deployment/pkg/a1stub/server.go:344 +0x8c
  | net/http.HandlerFunc.ServeHTTP(0x12f7140, 0x14b9de0, 0xc00016e000, 0xc0000ae100)
  | /usr/local/go/src/net/http/server.go:1995 +0x44
  | net/http.(*ServeMux).ServeHTTP(0xc0002ba480, 0x14b9de0, 0xc00016e000, 0xc0000ae100)
  | /usr/local/go/src/net/http/server.go:2375 +0x1d6
  | net/http.serverHandler.ServeHTTP(0xc0002b4680, 0x14b9de0, 0xc00016e000, 0xc0000ae100)
  | /usr/local/go/src/net/http/server.go:2774 +0xab
  | net/http.(*conn).serve(0xc0000381e0, 0x14be7a0, 0xc000572ac0)
  | /usr/local/go/src/net/http/server.go:1878 +0x84c
  | created by net/http.(*Server).Serve
  | /usr/local/go/src/net/http/server.go:2884 +0x2f4
  | [test harness] Received non-matching request &{GET /elasticsearch/_tasks/ HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[gzip] Content-Type:[application/json] User-Agent:[elastic/6.2.16 (linux-amd64)]] {} <nil> 0 [] false localhost:8080 map[] map[] <nil> map[] [::1]:44798 /elasticsearch/_tasks/ <nil> <nil> <nil> 0xc000083f40}
  | http: panic serving [::1]:44798: oops
  | goroutine 305 [running]:
  | net/http.(*conn).serve.func1(0xc00052bea0)
  | /usr/local/go/src/net/http/server.go:1769 +0xc9
  | panic(0x101a3e0, 0x1472090)
  | /usr/local/go/src/runtime/panic.go:522 +0x1b5
  | github.com/chef/automate/components/automate-deployment/pkg/a1stub.debug404Handler(0x14b9de0, 0xc00016e0e0, 0xc0002ae800)
  | /go/src/github.com/chef/automate/components/automate-deployment/pkg/a1stub/server.go:344 +0x8c
  | net/http.HandlerFunc.ServeHTTP(0x12f7140, 0x14b9de0, 0xc00016e0e0, 0xc0002ae800)
  | /usr/local/go/src/net/http/server.go:1995 +0x44
  | net/http.(*ServeMux).ServeHTTP(0xc0002ba480, 0x14b9de0, 0xc00016e0e0, 0xc0002ae800)
  | /usr/local/go/src/net/http/server.go:2375 +0x1d6
  | net/http.serverHandler.ServeHTTP(0xc0002b4680, 0x14b9de0, 0xc00016e0e0, 0xc0002ae800)
  | /usr/local/go/src/net/http/server.go:2774 +0xab
  | net/http.(*conn).serve(0xc00052bea0, 0x14be7a0, 0xc000361a40)
  | /usr/local/go/src/net/http/server.go:1878 +0x84c
  | created by net/http.(*Server).Serve
  | /usr/local/go/src/net/http/server.go:2884 +0x2f4
  | 0 / 100    0.00% 0s
```

**Comment by phiggins** [comment]
> [test harness] Received non-matching request &{GET /elasticsearch/_tasks/ HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[gzip] Content-Type:[application/json] User-Agent:[elastic/6.2.16 (linux-amd64)]] {} <nil> 0 [] false localhost:8080 map[] map[] <nil> map[] [::1]:44796 /elasticsearch/_tasks/ <nil> <nil> <nil> 0xc0000833c0}

From reading the logs it looks like there's some kind of fake elastic service being used in the tests, and since you've added an API call that wasn't happening before it's bombing out on that.

**Comment by lancewf** [comment]
@phiggins That never even crossed my mind. I was thinking it was using an old version of Elasticsearch. 
Thanks Pete!

**Comment by phiggins** [comment]
This was the big tipoff:

> [test harness] Starting stub elasticsearch api &{:8080 0xc0002ba480 <nil> 10s 0s 10s 0s 0 map[] <nil> 0xc000444000 0 0 {{0 0} 0} <nil> {0 0} map[] map[] <nil> []}

**Pull request merged**
