### PR TITLE
notifications slack integration broken image fix

### LINKED ISSUE #3602: Image URL included in Slack integration returns 404
## Describe the bug

When using the Slack integration, the `icon_url` provided returns a 404.

URL: https://docs.chef.io/_static/chef_logo_v2.png

## To Reproduce

- Setup Slack integration
- See the JSON body includes a URL to a missing image

## Expected behavior

- Expect the url provided in `icon_url` to actual resolve to an image that is accessible.

### PR DESCRIPTION
**Pull request by susanev**
### :nut_and_bolt: Description: What code changed, and why?
there was a broken image in the notifications service, we are gonna use this one instead https://docs.chef.io/images/chef-icon.png h/t @mjingle 

### :chains: Related Resources
fixes #3602 

### :+1: Definition of Done
no more broken image url

### :athletic_shoe: How to Build and Test the Change
i dont super know how to test this, hopefully @satellite15 does

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
zero.

### CODE REVIEW

**Comment by susanev** [comment]
no clue why im breaking doc shortcodes??

**Comment by schisamo** [comment]
Is there a way we can bake this image into the service? I don't want to hold up fixing this broken image but maybe we should have a follow-on PR which doesn't pull the image from an external location.

**Comment by susanev** [comment]
@schisamo i was under the assumption that it needed to be external... @satellite15 can it be internal to the service?

**Comment by satellite15** [comment]
I can't reproducing this. I see the icon on my slack channel before and after the fix.
In both cases it only appears on the first alert and not subsequent alerts.

I see the icon in the slack alerts before and after the fix.

And the URL is in s3.
before https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2017-02-17/143310324690_48.png

after https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2020-05-08/1136159172752_48.png

**Pull request merged**
