### PR TITLE
Stop Vendoring Go Dependencies

### PR DESCRIPTION
**Pull request by danielsdeleo**
### :nut_and_bolt: Description: What code changed, and why?

In #4298 I am making the external API a separate go module. Go modules vendoring doesn't make any special distinction for code in the same repo, which means that to propagate a change to the API, a developer must compile the updated protos and then revendor the dependencies to update the vendored copy. In response to this problem we can:

* Accept the need to revendor when updating the external API and let it be slow. It's slow because there's a lot of IO to the shared filesystem. It's also confusing that you have to update the local dependency. The latter problem can be somewhat mitigated by updating our studio tooling to compile the protos, but as you can see in this PR there's a lot of places where protos are built in a different way.
* Stop vendoring. The tradoffs for automate in general are:
  - (con) Updating dependencies no longer provides an easy way to review what is changing in those dependencies.
  - (con) We'll likely have to give up on rebuilding all affected components when a dependency changes. This means occasionally we could have build-breaks caused by a previous dependency update. (we might be able to do something here with changes to our existing tooling).
  - (con) More network resources required during the build (likely can be mitigated with some caching)
  - (pro) Fewer situations where people need to regenerate bldr.toml.
  - (pro) Likely makes it easier to split out more modules over time if we care to.
  - (pro) Less work when updating a dependency
* Attempt to create tooling to update the vendor dir quickly after compiling new protos. This likely involves doing unsupported things with the internals of the go module system.

This PR demonstrates removing the vendoring. A summary of the changes:
* Delete the vendor dir
* Update our revendor tooling to vendor external protobufs in a protovendor dir (it's renamed because the presence of a `vendor` directory may cause go tooling to behave in vendor mode). Modify protobuf build scripts to match
* Update docs, readmes, etc. that reference vendoring or give instructions for using `dep` 🙀 
* Update other scripts that assume the presence of the vendor dir.

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by stevendanna** [comment]
I am in general a proponent of vendoring where we can; but I think moving away from vendoring makes snese given the trade-offs we face.

It looks like the proxy tests are failing:

```
go: github.com/Azure/azure-sdk-for-go@v30.1.0+incompatible: Get https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/@v/v30.1.0+incompatible.mod: dial tcp: lookup proxy.golang.org on 127.0.0.11:53: read udp 127.0.0.1:38841->127.0.0.11:53: i/o timeout
```

My guess is this might be that we haven't set the proxy environment variables at the point when we now need them to contact the internet during the build.

**Comment by danielsdeleo** [comment]
> I am in general a proponent of vendoring where we can; but I think moving away from vendoring makes snese given the trade-offs we face.

I feel exactly the same. If the module system had a special case behavior to make local modules work less confusingly when vendoring then I would prefer to keep it. If it gains that ability in the future then I would like to change back to using vendoring. But with the current capabilities of the tools we're using, this seems least bad.

**Comment by lancewf** [comment]
I am having a problem building components. 
`build components/event-feed-service`
```
/src/api/interservice/authz/authz.pb.go:12:2: cannot find package "." in:
	/src/vendor/github.com/envoyproxy/protoc-gen-validate/validate
pkg/server/event_export.go:15:2: cannot find package "." in:
	/src/vendor/github.com/gocarina/gocsv
pkg/server/feed.go:7:2: cannot find package "." in:
	/src/vendor/github.com/gofrs/uuid
/src/api/interservice/authz/authz.pb.client_mock.go:10:2: cannot find package "." in:
	/src/vendor/github.com/golang/mock/gomock
/src/api/external/data_lifecycle/data_lifecycle.pb.gw.go:16:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/descriptor
/src/api/external/common/version/version.pb.go:10:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/proto
/src/api/external/annotations/iam/annotations.pb.go:11:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/protoc-gen-go/descriptor
/src/api/interservice/authz/authz.pb.validate.go:18:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes
/src/api/external/data_lifecycle/data_lifecycle.pb.go:13:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes/duration
/src/api/interservice/es_sidecar/service.pb.go:12:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes/empty
/src/api/interservice/event/event.pb.go:12:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes/struct
/src/api/interservice/authz/project.pb.go:13:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes/timestamp
/src/api/interservice/cereal/cereal.pb.go:13:2: cannot find package "." in:
	/src/vendor/github.com/golang/protobuf/ptypes/wrappers
/src/api/external/iam/v2/common/teams.pb.go:11:2: cannot find package "." in:
	/src/vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options
/src/api/external/data_lifecycle/data_lifecycle.pb.gw.go:18:2: cannot find package "." in:
	/src/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime
/src/api/external/data_lifecycle/data_lifecycle.pb.gw.go:19:2: cannot find package "." in:
	/src/vendor/github.com/grpc-ecosystem/grpc-gateway/utilities
/src/lib/tracing/tracer.go:7:2: cannot find package "." in:
	/src/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc
/src/lib/tracing/tracer.go:8:2: cannot find package "." in:
	/src/vendor/github.com/opentracing/opentracing-go
/src/lib/tls/certs/certs.go:10:2: cannot find package "." in:
	/src/vendor/github.com/pkg/errors
pkg/config/service.go:6:2: cannot find package "." in:
	/src/vendor/github.com/sirupsen/logrus
cmd/event-feed-service/commands/root.go:7:2: cannot find package "." in:
	/src/vendor/github.com/spf13/cobra
cmd/event-feed-service/commands/root.go:8:2: cannot find package "." in:
	/src/vendor/github.com/spf13/viper
/src/lib/cereal/cereal.go:15:2: cannot find package "." in:
	/src/vendor/github.com/teambition/rrule-go
/src/lib/tracing/tracer.go:9:2: cannot find package "." in:
	/src/vendor/github.com/uber/jaeger-client-go/config
/src/api/external/data_lifecycle/data_lifecycle.pb.go:15:2: cannot find package "." in:
	/src/vendor/google.golang.org/genproto/googleapis/api/annotations
/src/api/interservice/authz/authz.pb.client_mock.go:11:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc
/src/api/interservice/authz/authz.pb.go:15:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/codes
/src/lib/grpc/secureconn/factory.go:11:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/credentials
/src/api/external/data_lifecycle/data_lifecycle.pb.gw.go:22:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/grpclog
/src/lib/grpc/health/health.go:5:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/health
/src/lib/grpc/health/health.go:6:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/health/grpc_health_v1
/src/api/interservice/event_feed/event_feed.pb.client_mock.go:12:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/metadata
pkg/grpc/grpc.go:13:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/reflection
/src/api/interservice/authz/authz.pb.go:16:2: cannot find package "." in:
	/src/vendor/google.golang.org/grpc/status
/src/api/external/common/version/version.pb.go:11:2: cannot find package "." in:
	/src/vendor/google.golang.org/protobuf/reflect/protoreflect
/src/api/external/common/version/version.pb.go:12:2: cannot find package "." in:
	/src/vendor/google.golang.org/protobuf/runtime/protoimpl
/src/lib/elasticutil/tasks.go:8:2: cannot find package "." in:
	/src/vendor/gopkg.in/olivere/elastic.v6
   event-feed-service: Build time: 0m20s
   event-feed-service: Exiting on error
```

**Comment by danielsdeleo** [comment]
@lancewf make sure to restart your studio or at least unset the `GOFLAGS`

**Comment by lancewf** [comment]
@danielsdeleo I exited out of the studio and created a new one and I am still getting the same errors.

**Comment by danielsdeleo** [comment]
> @danielsdeleo I exited out of the studio and created a new one and I am still getting the same errors.

Ah, it's a bootstrapping issue with the go scaffolding. You need to have this change reflected in the scaffolding you're using: https://github.com/chef/automate/pull/4314/commits/6fde8358896d2552855581cba9c764c7af62d683#diff-fb20abf751f66696b964ee39ff15d251L37 (which would happen automatically if we merged this and published the packages to dev).

To do it on the branch, you can first `build components/automate-scaffolding-go/`, you may need to `hab pkg install results/YOU-automate-scaffolding-go-ETC`, then `export local_scaffolding_origin=YOUR_ORIGIN`

**Comment by lancewf** [comment]
@danielsdeleo The scaffolding change fixed the problem.

**Comment by danielsdeleo** [comment]
I think the day-to-day impact will mostly be the time you have to wait for go modules to download. I have run `hab studio run 'hab pkg install -bf core/go; time go mod download' ` a few times and gotten results in the 30-40s range. Note that you only download stuff once and then it's cached. 30-40 seconds of downloading time is definitely less good than zero, but I think it's acceptable. For comparison, it takes about 30 to get hab dependencies for one of our projects (uncached) and 15 seconds to get them again (packages cached). If it's really annoying to folks, we could look for a way to persist the module cache between studio sessions.

**Review by lancewf — APPROVED** [review]
It worked for me. Let's give it a try. 👍

**Pull request merged**
