### PR TITLE
adjust apis so that they document the proper return structs

### PR DESCRIPTION
**Pull request by rickmarry**
Signed-off-by: Rick Marry <rmarry@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
Currently the ListReports API, through it's swagger documentation, is a bit misleading as it shows the response as returning more fields than it actually does, or at least populates with good data.  The problem stems from the fact that we were reusing a proto message which we simply didn't populate all fields for.  Though this seems harmless enough, it leads users into believing that more info is available than there actually is on the response.  The current response may look like this for instance:

```json
{
  "reports": [
    {
      "id": "44024b50-2e0d-42fa-a57c-dddddddddddd",
      "node_id": "34cbbb4c-c502-4971-b193-00e987b4678c",
      "node_name": "debian(2)-zeta-linux(f)-apache(p)-failed",
      "end_time": "2021-06-23T23:59:50Z",
      "status": "failed",
      "controls": {
        "total": 59,
        "passed": {
          "total": 23
        },
        "skipped": {
          "total": 12
        },
        "failed": {
          "total": 21,
          "minor": 0,
          "major": 0,
          "critical": 21
        },
        "waived": {
          "total": 3
        }
      },
      "environment": "",
      "version": "",
      "platform": null,
      "statistics": null,
      "profiles": [],
      "job_id": "",
      "ipaddress": "127.0.0.1",
      "fqdn": "",
      "chef_server": "",
      "chef_organization": "",
      "roles": [],
      "chef_tags": [],
      "projects": [],
      "status_message": ""
    }
  ],
  "total": 1
}
```
the following fields are never populated with real data and this is by design to keep the response small for this API
```
      "environment": "",
      "version": "",
      "platform": null,
      "statistics": null,
      "profiles": [],
      "job_id": "",
      "fqdn": "",
      "chef_server": "",
      "chef_organization": "",
      "roles": [],
      "chef_tags": [],
      "projects": [],
      "status_message": ""
```

this PR changes the response to look more like this:

```json
{
  "reports": [
    {
      "id": "44024b50-2e0d-42fa-a57c-dddddddddddd",
      "node_id": "34cbbb4c-c502-4971-b193-00e987b4678c",
      "node_name": "debian(2)-zeta-linux(f)-apache(p)-failed",
      "end_time": "2021-06-23T23:59:50Z",
      "status": "failed",
      "controls": {
        "total": 59,
        "passed": {
          "total": 23
        },
        "skipped": {
          "total": 12
        },
        "failed": {
          "total": 21,
          "minor": 0,
          "major": 0,
          "critical": 21
        },
        "waived": {
          "total": 3
        }
      },
      "ipaddress": "192.168.56.33"
    }
  ],
  "total": 1
}
```
*The swagger doc will reflect this also

### :athletic_shoe: How to Build and Test the Change
 from within hab run the following:
 ```
 start_all_services
 rebuild components/automate-deployment
 rebuild components/automate-gateway
 rebuild components/compliance-service
 ```

once all are rebuilt, you can run the following from within hab to load some reports

`load_compliance_reports`
call the API with endpoint:  api/v0/compliance/reporting/reports 

observe that the response now has only the appropriate fields
```

<!-- /!\ Please ensure that you are NOT disclosing any customer information without their consent /!\ -->

### :chains: Related Resources

### :+1: Definition of Done

### :athletic_shoe: How to Build and Test the Change

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ ] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ ] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ ] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [ ] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [ ] Tests added/updated? (all new code needs new tests)
- [ ] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable

### CODE REVIEW

**Review by kagarmoe — APPROVED** [review]

**Comment by kagarmoe** [comment]
You need to `make sync_swagger_files` to pick up the doc changes.

**Comment by kalroy** [comment]
@kagarmoe Executed `make sync_swagger_files` but cannot see the changes reflected in netlify.

**Review by kalroy — CHANGES_REQUESTED** [review]
Docs changes should reflect in netlify preview.

**Review by kalroy — APPROVED** [review]

**Comment by kalroy** [comment]
> Docs changes should reflect in netlify preview.

The docs changes can now be seen in netlify after running the correct command

**Pull request merged**
