### PR TITLE
ami filters removed

### PR DESCRIPTION
**Pull request by iamazzeez**
Signed-off-by: Abdul-Az <aazeez@progress.com>
https://chefio.atlassian.net/browse/KINETICS-211

### :nut_and_bolt: Description: What code changed, and why?
Removed Ami filters options from config file.

### :+1: Definition of Done
`chef-automate init-config-ha aws`
will not have ami filters 

### :athletic_shoe: How to Build and Test the Change
rebuild components/automate-cli
and run `chef-automate init-config-ha aws`
ami filters will not be available

### :white_check_mark: Checklist

**All PRs** must tick these:

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

With occasional exceptions, all PRs **from Progress employees** must tick these:

- [x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [x] Spelling, grammar, typos checked? *(at a minimum use `make spell` in any component directory)*
- [x] Code well-formatted? *(indents, line breaks, etc. improve rather than hinder readability)*

All PRs **from Progress employees** should tick these if appropriate:

- [x] Tests added/updated? (all new code needs new tests)
- [x] Docs added/updated? (all customer-facing changes)

*Please add a note next to any checkbox above if you are NOT ticking it.*

### :camera: Screenshots, if applicable
Before change `chef-automate init-config-ha aws` will display config as shown below

Screenshot 2022-09-13 at 5 06 46 PM

After change `chef-automate init-config-ha aws` will display config as shown below

Screenshot 2022-09-13 at 5 07 44 PM

### CODE REVIEW

**Review by Dmaddu — APPROVED** [review]

**Review by punitmundra — CHANGES_REQUESTED** [review]
please these remove these variable ami_filter_name = ""
ami_filter_virt_type,
ami_filter_owner from terrform code

**Review by punitmundra — CHANGES_REQUESTED** [review]
@iamazzeez : after the code change please do the deployment and make sure that, the deployment will be successful

**Comment by iamazzeez** [comment]
> please these remove these variable ami_filter_name = "" ami_filter_virt_type, ami_filter_owner from terrform code

@punitmundra I have added those changes in different pr, https://github.com/chef/automate/pull/7416 i've also deployed the code it was successful.

**Comment by Dmaddu** [comment]
these changes are made in PR https://github.com/chef/automate/pull/7416. Hence closing this PR

**Pull request closed without merging**
